# Official Bun image - https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1
WORKDIR /usr/src/app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY ./packages ./packages
COPY ./src ./src

USER bun
CMD [ "bun", "run", "dev:watch" ]
