name: Publish changelog
permissions:
  contents: write

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
  push:
    branches: ['main']
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-22.04
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout config
        uses: actions/checkout@v4
        with:
          repository: trackedout/dunga-dunga-backend
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: cliff-config
          fetch-depth: 0

      - name: Generate changelog for tag
        uses: orhun/git-cliff-action@main
        if: startsWith(github.ref, 'refs/tags/')
        id: git-cliff
        with:
          config: cliff-config/cliff.toml
          args: --strip all -v --latest --github-repo ${{ github.repository }}

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          make_latest: false
          body_path: ${{ steps.git-cliff.outputs.changelog }}

      - name: Generate entire changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff-all
        with:
          config: cliff.toml
          args: --strip all -v --github-repo ${{ github.repository }}

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          name: latest
          tag_name: latest
          make_latest: true
          body_path: ${{ steps.git-cliff-all.outputs.changelog }}
